spring.application.name=EcomProject


spring.datasource.url=jdbc:postgresql://localhost:5433/database1
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#first create a table and then initialise a data
spring.jpa.defer-datasource-initialization=true   



#Redis properties
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000